"""new

Revision ID: 40b7695ad993
Revises: 894aa56598f5
Create Date: 2025-12-09 17:22:04.928842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b7695ad993'
down_revision: Union[str, Sequence[str], None] = '894aa56598f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'api_id',
               existing_type=sa.VARCHAR(length=130),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'api_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=130),
               existing_nullable=False)
    # ### end Alembic commands ###
