"""new

Revision ID: 6a956616d58c
Revises: d5fb837bf582
Create Date: 2025-12-09 19:06:37.740214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a956616d58c'
down_revision: Union[str, Sequence[str], None] = 'd5fb837bf582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('public_api_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_api_keys_public_api_id'), 'api_keys', ['public_api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_public_api_id'), table_name='api_keys')
    op.drop_column('api_keys', 'public_api_id')
    # ### end Alembic commands ###
