"""new

Revision ID: 894aa56598f5
Revises: 2484cbd7ddbd
Create Date: 2025-12-09 17:20:18.476564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894aa56598f5'
down_revision: Union[str, Sequence[str], None] = '2484cbd7ddbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'api_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=130),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'api_id',
               existing_type=sa.String(length=130),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
