"""new

Revision ID: d5fb837bf582
Revises: 6f755ac29aa9
Create Date: 2025-12-09 17:33:20.245059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fb837bf582'
down_revision: Union[str, Sequence[str], None] = '6f755ac29aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('api_key', sa.String(length=200), nullable=False))
    op.add_column('api_keys', sa.Column('masked_key', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_api_keys_api_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=False)
    op.create_index(op.f('ix_api_keys_masked_key'), 'api_keys', ['masked_key'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['user_id'])
    op.drop_column('api_keys', 'api_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('api_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_masked_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_api_id'), 'api_keys', ['api_id'], unique=False)
    op.drop_column('api_keys', 'masked_key')
    op.drop_column('api_keys', 'api_key')
    # ### end Alembic commands ###
